mainWindowTitle: SIP Analyzer
mainWindowSize: 800x500
savedDatabase: test.db
savedDatabaseQuery: SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;
packetRegex: ^(.*)
packetID: 
savedLogPath: C:/Users/johan.andersson/Desktop/seb.log
