mainWindowTitle: SIP Analyzer
mainWindowSize: 1200x800
savedDatabase: megatest.db
savedDatabaseQuery: SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;
packetRegex: ^(.*)
packetID: 
savedLogPath: C:/Users/johan.andersson/Desktop/seb.log
SipTable: CREATE TABLE Call(id INT PRIMARY KEY NOT NULL, call_id BLOB, from_header BLOB, to_header BLOB, packet BLOB)
